stage/testnet/main deployments/upgrades hardhat tasks support
quash 74bdd53 test

diff --git a/scripts/deploy_manager b/scripts/deploy_manager
--- a/scripts/deploy_manager
+++ b/scripts/deploy_manager
@@ -2,7 +2,9 @@
 
 ABIDIR=""
 ACTION=""
-NETWORK="localhost"
+NETWORK=""
+CONTRACT=""
+ENVIRONMENT="develop"
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 VERSIONTYPE=""
 
@@ -21,14 +23,18 @@ help() {
   echo "  sh deploy_manger [-n|--network] [-a|--action] [-t|--version-type]"
   echo
   echo "Options:"
-  echo "-n,--network <network>"
-  echo "      Target network to run the deployment / upgrade."
-  echo "      Possible values: [goerli | mainnet | localhost]"
-  echo "      If ommited, defaults to localhost."
+  echo "-e,--environment <environment>"
+  echo "      Target environment to run the deployment / upgrade."
+  echo "      Possible values: [develop | stage | testnet | main]"
+  echo "      If ommited, defaults to develop."
   echo
-  echo "-a,--action <date>"
+  echo "-a,--action <action>"
   echo "      Action to perform."
   echo "      Possible values: [deploy | upgrade]"
+  echo
+  echo "-c,--contract <contract>"
+  echo "      Contract to be used with the upgrade action."
+  echo "      Possible values: [ssvnetwork | ssvnetworkviews]"
   echo
   echo "-t,--version-type [major|minor|patch]"
   echo "      Type of semantic version to create. Valid options are 'major', 'minor' or 'patch'"
@@ -37,7 +43,7 @@ help() {
   echo "          patch: Will bump up to next patch release (i.e v1.0.2 -> v1.0.3)"
   echo "      Rules:"
   echo "      Tags created using 'stage' branch are treated as RCs (i.e v0.1.0-rc.0 -> v0.1.0-rc.1 ...)"
-  echo "      Tags created using 'main' branch are treated as releases (i.e v0.1.0-rc.1 becomes v0.1.0)"
+  echo "      Tags created using 'testnet' or 'main' branches are treated as releases (i.e v0.1.0-rc.1 becomes v0.1.0)"
   echo "      In both cases, if a version-type parameter is passed, the rule is override (i.e v0.1.0-rc.2 -> -t minor -> v0.2.0-rc.0)"
   echo "      Tags created using 'develop' branch are not tagged"
   echo "      If ommited, will default to current version"
@@ -53,14 +59,17 @@ while [[ "$#" -gt 0 ]]; do
     help
     exit
     ;;
-  -n | --network)
-    NETWORK=$2
+  -e | --environment)
+    ENVIRONMENT=$2
     ;;
   -t | --version-type)
     VERSIONTYPE=$2
     ;;
   -a | --action)
     ACTION=$2
+    ;;
+  -c | --contract)
+    CONTRACT=$2
     ;;
   esac
   shift
@@ -71,13 +80,21 @@ if [ "$ACTION" == "" ]; then
   exit 1
 fi
 
-# Get the list of branches from the repository
-BRANCHES=$(git branch --format='%(refname:short)' | grep -E '^(develop|stage|main)$')
-select BRANCH in $BRANCHES; do
-  if [ ! -z "$BRANCH" ]; then
-    break
-  fi
-done
+if [ "$ENVIRONMENT" == "stage" ]; then
+  BRANCH="stage"
+  NETWORK="goerli"
+elif [ "$ENVIRONMENT" == "testnet" ]; then
+  BRANCH="testnet"
+  NETWORK="goerli"
+elif [ "$ENVIRONMENT" == "main" ]; then
+  BRANCH="main"
+  NETWORK="mainnet"
+else
+  BRANCH="develop"
+  NETWORK="goerli"
+fi
+
+echo "Using branch $BRANCH for environment $ENVIRONMENT"
 
 run_command() {
   if ! "$@"; then
@@ -93,8 +110,8 @@ run_command npm ci -q --no-progress
 # Compile project
 run_command npx hardhat compile --force
 
-# Only deployments for stage and main branches are tagged
-if [[ $BRANCH == "stage" || $BRANCH == "main" ]]; then
+# Only deployments for stage, testnet and main branches are tagged
+if [[ $BRANCH == "stage" ||  $BRANCH == "testnet" || $BRANCH == "main" ]]; then
   run_command source ./tag-version -b "$BRANCH" -n -t "$VERSIONTYPE"
 else
   TAGVERSION="dev"
@@ -102,28 +119,31 @@ fi
 
 if [ "$ACTION" == "deploy" ]; then
   # Run script to deploy the contracts
-  run_command npx hardhat --network "$NETWORK" deploy:contracts --tag "$TAGVERSION"
+  run_command npx hardhat --network "$NETWORK" deploy:all --tag "$TAGVERSION"
 elif [ "$ACTION" == "upgrade" ]; then
-  # Run script to upgrade the contracts
-  run_command npx hardhat --network "$NETWORK" upgrade:Lock --tag "$TAGVERSION"
+  if [[ "$CONTRACT" == "ssvnetwork" || "$CONTRACT" == "ssvnetworkviews" ]]; then
+    # Run script to upgrade the contracts
+    run_command npx hardhat --network "$NETWORK" upgrade:"$CONTRACT" --tag "$TAGVERSION"
+  else
+    echo "-- ERROR: Wrong CONTRACT value for upgrade action"
+    exit 1
+  fi
 else
   echo "-- ERROR: Wrong ACTION value. Possible values: [deploy | upgrade]"
   exit 1
 fi
 
-if [[ $NETWORK == "mainnet" || $NETWORK == "goerli" ]]; then
+if [[ "$ENVIRONMENT" == "stage" || "$ENVIRONMENT" == "testnet" || "$ENVIRONMENT" == "main" ]]; then
 
   # Update .openzeppelin metadata
   run_command git add .openzeppelin/"$NETWORK".json
   run_command git commit -m "Update .openzeppelin folder"
   run_command git push -u origin $branch
 
-  if [[ $BRANCH == "stage" || $BRANCH == "main" ]]; then
-    run_command source ./tag-version -b "$BRANCH" -t "$VERSIONTYPE"
-  fi
-  ABIDIR="docs/$NETWORK/abi/$TAGVERSION"
+  run_command source ./tag-version -b "$BRANCH" -t "$VERSIONTYPE"
+  ABIDIR="docs/$ENVIRONMENT/abi/$TAGVERSION"
 
-  run_command git checkout gh-pages
+  run_command git checkout contract-abi
 
   # Publish the ABI to a specific GitHub Pages location
   mkdir -p $ABIDIR
@@ -131,7 +151,7 @@ if [[ $NETWORK == "mainnet" || $NETWORK == "goerli" ]]; then
 
   run_command git add $ABIDIR
   run_command git commit -m "Publish ABI for deployment to $NETWORK"
-  run_command git push -u -f origin gh-pages
+  run_command git push -u -f origin contract-abi
 fi
 
 run_command git checkout $CURRENT_BRANCH
